node{
   
    stage('build'){
        
            bat '''cd C:\\Users\\tfssetup\\Desktop\\docker\\aspnetapp
            dotnet restore
            dotnet publish -c Release -o C:\\Users\\tfssetup\\Desktop\\docker\\Artifact'''

    }
    stage('Build Docker Image'){
        bat 'C:\\Users\\tfssetup\\Desktop\\docker\\test\\build_docker_image.bat'
    }
    stage('Deploy to Dev'){
        bat '''set KUBECONFIG=C:\\Users\\tfssetup\\.kube\\config
        kubectl describe deploy pearson-dev
            kubectl set deployments/pearson-dev pearson-dev=deploymentimagerepo.azurecr.io/testapp_%BUILD_NUMBER%
            kubectl describe deployments pearson-dev'''
            timeout(time: 5, unit: 'MINUTES'){
                input 'Do you want to deploy artifacts into QA?'
            }
    }
    stage('Deploy to QA'){
        bat ''' set KUBECONFIG=C:\\Users\\tfssetup\\.kube\\config
            kubectl describe deploy pearson-qa
            kubectl set image deployments/pearson-qa pearson-qa=deploymentimagerepo.azurecr.io/testapp_%BUILD_NUMBER%
            kubectl describe deploy pearson-qa'''
    }
}